---
  - name: Spot Request Creation with more options
    amazon.aws.ec2_spot_instance:
      launch_specification:
        image_id: ami-051f8a213df8bc089
        key_name: local
        instance_type: t2.micro
        block_device_mappings:
          - device_name: /dev/sdb
            ebs:
              delete_on_termination: true
              volume_type: gp3
              volume_size: 5